# Generated by Django 5.0.3 on 2024-03-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_patient_student_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="year_of_study",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
